language: cpp
compiler:
    - gcc
before_install:
    # disable rvm, use system Ruby
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "rake yast2-devtools yast2 yast2-core-dev libslp-dev" -g "rspec:3.3.0 yast-rake gettext simplecov coveralls:0.8.10"
script:
    - rake check:syntax
    - rake check:pot
    - make -f Makefile.cvs
    - make
    - sudo make install
    - make check

